name: todaytest
description: A new Flutter project.
publish_to: "Biobytes"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  go_router:
  screenshot:
  flutter_svg:
  image_gallery_saver:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/font/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/font/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/font/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/font/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/font/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSansKR-Black.ttf
          weight: 900
